# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 191))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 220, 371, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.first = QtWidgets.QPushButton(self.widget)
        self.first.setObjectName("first")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.first)
        self.horizontalLayout.addWidget(self.first)
        self.second = QtWidgets.QPushButton(self.widget)
        self.second.setObjectName("second")
        self.buttonGroup.addButton(self.second)
        self.horizontalLayout.addWidget(self.second)
        self.third = QtWidgets.QPushButton(self.widget)
        self.third.setObjectName("third")
        self.buttonGroup.addButton(self.third)
        self.horizontalLayout.addWidget(self.third)
        self.fourth = QtWidgets.QPushButton(self.widget)
        self.fourth.setObjectName("fourth")
        self.buttonGroup.addButton(self.fourth)
        self.horizontalLayout.addWidget(self.fourth)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ImageLabel"))
        self.first.setText(_translate("Dialog", "First"))
        self.second.setText(_translate("Dialog", "Second"))
        self.third.setText(_translate("Dialog", "Third"))
        self.fourth.setText(_translate("Dialog", "Fourth"))


class MonApplication(QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.ui.first.clicked.connect(self.on_first_click)

    def on_first_click(self):
        print("Bouton first cliqué !")
        self.ui.label.setText("Le bouton a été actionné !")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MonApplication()
    window.show()
    sys.exit(app.exec_())

